### ISSUE TITLE
 Secrets object is not correctly specified in config. It can only contain string values, How i can fix this?

### ISSUE THREAD

**Issue by harshmittal1750** [smartcontractkit/functions-insurance#4]
`npx hardhat functions-request --network sepolia --contract 0x6773a38a1dC2A133dda0E3Ca46092a828Ec686C6 --subid 391`

> secp256k1 unavailable, reverting to browser version
> An unexpected error occurred:
> 
> Error: Secrets object is not correctly specified in config. It can only contain string values.
>     at getRequestConfig (D:\functions-insurance\FunctionsSandboxLibrary\getRequestConfig.js:41:15)
>     at SimpleTaskDefinition.action (D:\functions-insurance\tasks\Functions-client\request.js:73:27)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Environment._runTaskDefinition (D:\functions-insurance\node_modules\hardhat\src\internal\core\runtime-environment.ts:330:14)
>     at Environment.run (D:\functions-insurance\node_modules\hardhat\src\internal\core\runtime-environment.ts:163:14)
>     at main (D:\functions-insurance\node_modules\hardhat\src\internal\cli\cli.ts:277:7)

**Comment by harshmittal1750** [comment]
Just change the WORLD_WEATHER_ONLINE_API_KEY to WORLD_WEATHER_API_KEY in .env
